engines:
    eslint:
        enabled: true
    csslint:
        enabled: false
        checks:
            box-sizing:
                enabled: false
    duplication:
        enabled: true
        config:
            languages:
            - javascript:
ratings:
    paths:
    - "src/**"
    - "**.js"
